PREVIEW_LENGTH = 512#characters

# I/O
CONVERT_IGNORE_LIST_FILE    = ".convertignore"
BUILT_HTML_EXTENSION        = ".md.html"
DEFAULT_TEMPLATE_FILE       = "template.html"
DEFAULT_GLOBAL_CSS_FILE     = "global.css"
DEFAULT_GLOBAL_JS_FILE      = "global.js"

# Classes
EMBED_MARKDOWN_CLASS        = "embed-markdown"
EMBED_IMAGE_CLASS           = "embed-image"
EMBED_IMAGE_DATA_WIDTH      = "data-width"
EMBED_AUDIO_CLASS           = "embed-audio"
EMBED_VIDEO_CLASS           = "embed-video"
EMBED_PDF_CLASS             = "embed-pdf"
INTERNAL_LINK_CLASS         = "link-internal"
EXTERNAL_LINK_CLASS         = "link-external"
WIKILINK_LINK_CLASS         = "link-wikilink"
NOREF_WIKILINK_CLASS        = "link-wikilink-noref"
NOREF_WIKILINK_HREF         = "#"
TAGS_CLASS                  = "obsi-tag"
TAGS_DATA                   = "data-tag"
CODE_LANG_CLASS_PREFIX      = "language-"
CODE_BLOCK_CLASS            = "code-block"
CODE_INLINE_CLASS           = "code-inline"
CALLOUT_CLASS               = "callout"
CALLOUT_TITLE_CLASS         = "callout-title"
CALLOUT_CONTENT_CLASS       = "callout-content"
CALLOUT_TYPE_CLASS_PREFIX   = "callout-"
CALLOUT_TYPE_DATA           = "data-callout-type"
MATH_BLOCK_CLASS            = "math-block"
MATH_INLINE_CLASS           = "math-inline"